version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "Setting environment variables"
      - export SERVER_PORT=${SERVER_PORT}
      - export DATABASE_HOST=${DATABASE_HOST}
      - export DATABASE_PORT=${DATABASE_PORT}
      - export DB=${DB}
      - export DATABASE_USERNAME=${DATABASE_USERNAME}
      - export DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - export BUCKET_NAME=${BUCKET_NAME}
      - export REGION=${REGION}
      - export ACCESS_KEY=${ACCESS_KEY}
      - export SECRET_KEY=${SECRET_KEY}
      - echo "Granting execute permission to gradlew"
      - chmod +x gradlew

  build:
    commands:
      - echo "Building the project"
      - ./gradlew build
      - echo "Moving the built jar file"
      - ls build/libs
      - mv build/libs/*.jar app.jar

artifacts:
  files:
    - app.jar
