version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - echo "Granting execute permission to gradlew"
      - chmod +x gradlew

  build:
    commands:
      - ./gradlew build
      - mv build/libs/*.jar app.jar

artifacts:
  files:
    - app.jar
